---
# This playbook installs tools

- name: Install git 
  apt: name=git-core state=present update_cache=yes

- name: Install curl 
  apt: name=curl state=present

- name: Install vim 
  apt: name=vim state=present

- name: Install zip 
  apt: name=zip state=present

- name: Install ufw
  apt: name=ufw state=present

- name: Allow ssh through firewall
  ufw: proto=tcp port=22 rule=allow

- name: Set ufw policy
  ufw: state=enabled direction=incoming policy=deny
